### ISSUE TITLE
Enable proper TLS

### ISSUE THREAD

**Issue by svenstaro** [ivmarkov/rust-esp32-std-demo#81] opened 2022-04-24 16:40 UTC
It seems like the [original issue](https://github.com/espressif/esp-idf/issues/7631) for why TLS was disabled in the first place has been resolved with esp-idf 4.4 (which has been released). Is it now feasible to turn on TLS with proper verification and certificates?

**Comment by ivmarkov** [comment] 2022-04-24 17:59
Yes, I believe so. I'll turn it on for my own purposes likely in ~ 2 months from now (overwhelmed with other stuff). If you need it sooner, I'll gladly accept a PR!

**Comment by svenstaro** [comment] 2022-04-24 18:02
Already tried and it's "easy" to turn on but there's this blocker currently: https://github.com/esp-rs/esp-idf-svc/issues/67

**Comment by ivmarkov** [comment] 2022-04-24 18:14
Ok so it is not exposed by esp-idf-svc, sure. Vut is it also not exposed by esp-idf-sys?

**Comment by svenstaro** [comment] 2022-04-24 18:18
It's not exposed as far as I can see. Furthermore, since it's marked `extern` and it's inline asm I think there's no good way to expose it since it's needed at link time. This is currently a bit over my head.

**Comment by ivmarkov** [comment] 2022-04-25 17:53
Dupe of https://github.com/esp-rs/esp-idf-svc/issues/67

**Closed by ivmarkov** 2022-04-25 17:53 UTC
