### ISSUE TITLE
Could not find specification for target "xtensa-esp32-espidf"

### ISSUE THREAD

**Issue by godefroi** [ivmarkov/rust-esp32-std-demo#20] opened 2021-10-14 00:00 UTC
I followed the instructions in the README file, but I get this:

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names --target xtensa-esp32-espidf --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: Error loading target specification: Could not find specification for target "xtensa-esp32-espidf". Run `rustc --print target-list` for a list of built-in targets
```

I believe that this is related to the fact that `rustup toolchain show` does not list an `esp` toolchain:

```
$ rustup toolchain list
stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)
```

I did follow the directions on how to install this toolchain, and indeed the toolchain zipfile did get extracted to the correct place:

```
$ ls C:\Users\me\.rustup\toolchains\

    Directory: C:\Users\me\.rustup\toolchains

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           9/15/2021 12:26 PM                esp
d----            5/5/2021  8:28 AM                stable-x86_64-pc-windows-msvc
-a---          10/13/2021  5:41 PM      105402674 rust-1.55.0-dev-x86_64-pc-windows-msvc.zip
```

However, that directory being there is not enough to cause `rustup default esp` to succeed:

```
$ rustup default esp
error: toolchain 'esp' is not installed
```

**Comment by godefroi** [comment] 2021-10-15 02:21
@georgik I followed those exact instructions, with the same result:

```
$ cargo +esp build
error: toolchain 'esp' is not installed
```

**Comment by godefroi** [comment] 2021-10-15 14:08
@georgik yes, just Windows Defender. I think the problem here is that simply extracting the files doesn't lead `rustup` to believe that the toolchain is "installed". For example, in `install-rust-toolchain.sh`, we have the line:
```
./${RUST_DIST}/install.sh --destdir=${TOOLCHAIN_DESTINATION_DIR} --prefix="" --without=rust-docs
```
... and there is no equivalent line in `Install-RustToolchain.ps1`. I assume that whatever `install.sh` is doing is "registering" the toolchain with `rustup`?

**Comment by georgik** [comment] 2021-10-15 17:47
@godefroi Interesting. It seems that some kind of setup is leaking from previous installation. I've already noticed it with cargo and older version of toolchainn.
May I ask you just try to rename or delete  `~/.cargo` and `~/.rustup`.
Then download latest version of the install PowerShell script and run it. I've added speed up of download to the latest version.

**Comment by pekkah** [comment] 2021-10-16 15:50
By the way  the esp-idf windows setup has an option to install the experimental rust support. I think my esp toolchain came from there even though I might have later run that ps1 script from repo above.

**Comment by georgik** [comment] 2021-10-18 10:24
@godefroi Thank you for the log information. I see what might be the problem.
Right now the installation script assumes that rustup is installed in user's home. You're probably using different location.
What's the output of `(Get-Command rustup).path` ?

@pekkah Yep, I'm working on this feature in the idf-installer. Basically the PS1 script is right now the more advanced version of installation script. I plan to add some corrections to the Rust installer.

**Comment by grbd** [comment] 2021-11-27 02:13
As a suggestion it might be an idea to add a file to the root of the project called **rust-toolchain.toml**
with the following in
```
[toolchain]
channel = "esp"
```

For others to install the toolchain under windows one idea would be to look here

  * https://github.com/esp-rs/rust-build/releases/tag/v1.56.0.1
  * https://github.com/esp-rs/rust-build/releases/download/v1.56.0.1/rust-1.56.0.1-x86_64-pc-windows-msvc.zip

extract the zip then use
```
rustup toolchain link esp <extractedpath>
```
To register the toolchain as "esp" in the list of available toolchains

**Comment by ivmarkov** [comment] 2021-12-26 08:13
I'm not sure - is this fixed now, or is there a workaround? @godefroi ?

**Comment by godefroi** [comment] 2021-12-27 10:59
I haven't been working on this recently, sorry. I didn't find a workaround, and I'm out of town for some time.

**Comment by ivmarkov** [comment] 2022-01-14 17:53
Closing this as there is no activity on this topic, and hopefully the issue is resolved in the latest Espressif Rust 1.58 build. If it is not, please reopen the issue here: https://github.com/esp-rs/rust-build

**Closed by ivmarkov** 2022-01-14 17:53 UTC

**Comment by keredson** [comment] 2023-09-27 17:22
I had the same error, but on linux (Ubuntu 23.04).  Installed w/:
- `sudo apt install -y git curl gcc clang ninja-build cmake libudev-dev unzip xz-utils python3 python3-pip python3-venv libusb-1.0-0 libssl-dev pkg-config`
- `sudo snap install rustup --classic`
- `rustup install stable`
- `cargo install espup`
- `espup install`
- `. $HOME/export-esp.sh`

Version: `rustup 1.24.3 (ce5817a94 2021-05-31)`

```
$ cargo build
error: failed to run 'rustc' to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/derek/snap/rustup/common/rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names --target xtensa-esp32-espidf --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=split-debuginfo --print=crate-name --print=cfg` (exit status: 1)
  --- stderr
  error: Error loading target specification: Could not find specification for target "xtensa-esp32-espidf". Run `rustc --print target-list` for a list of built-in targets

$ rustup default esp
error: toolchain 'esp' is not installed
$ rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu
```

`~/.rustup/toolchains/esp` exists, so ran: `rustup toolchain link esp ~/.rustup/toolchains/esp`

This worked.  Ex:
```
~/projects/rust-esp32-std-demo$ cargo build
   [...]
    Finished dev [optimized + debuginfo] target(s) in 3m 42s
```

**Comment by Tevz-Beskovnik** [comment] 2024-04-16 20:18
Did anyone have this issue on MacOS (Sonoma 14.4.1)? I have esp in my toolchains however cannot get it to work, tried runnig above command and get the error that the toolchain is not installable. Don't really know how to proceed here.
