### ISSUE TITLE
Abort from test_threads() on ESP32-C3

### ISSUE THREAD

**Issue by sirhcel** [ivmarkov/rust-esp32-std-demo#44] opened 2021-12-20 17:08 UTC
Attempting to run the demo as of [0d085d7](https://github.com/ivmarkov/rust-esp32-std-demo/tree/0d085d70cbf50a7f1b321ac71195961183c38131), I'm getting an abort from [`test_threads()`](https://github.com/ivmarkov/rust-esp32-std-demo/blob/0d085d70cbf50a7f1b321ac71195961183c38131/src/main.rs#L324):
```
[...]
Rust main thread: Thread { id: ThreadId(1), name: Some("main"), .. }
Main TLS before change: 13
Main TLS after change: 42
This is thread number 0, Thread { id: ThreadId(2), name: None, .. }
Inner TLS: 0
abort() was called at PC 0x40380ff5 on core 0
[...]
```
A full log is shown in https://gist.github.com/sirhcel/bf55cb77898cb1e45d25e4eb1c66433d. I've seen this behavior with Rust 1.59.0 and 1.58.0 nightlies.

Just commenting out the invocation of `test_threads()` makes this demo run:
* Connects to WiFi
* Succesfully pings external host
* Reacts on the echo server on port 8080
* Serves via HTTP on port 80

**Comment by ivmarkov** [comment] 2021-12-25 20:25
Duplicate of #45.

**Closed by ivmarkov** 2021-12-25 20:25 UTC
