### ISSUE TITLE
Error building in Podman

### ISSUE THREAD

**Issue by oscartbeaumont** [ivmarkov/rust-esp32-std-demo#55] opened 2022-01-28 16:50 UTC
I am having an issue building this repository and was wondering if you could help me fix it.

I am confused about where the patches the error refers to are created, so I am a bit lost on how to fix this issue. It also says PlatformIO isn't installed in the directory but the CLI commands for PlatformIO exist in the directory and work correctly.

To get the error I clone in the repository and run `cargo build`. I am testing on Linux within a podman container provided [here](https://github.com/esp-rs/rust-build).

<details>
  <summary>The Error</summary>
  
```bash
Initialized empty Git repository in /opt/rust-esp32-std-demo/.embuild/platformio/packages/framework-espidf/.git/
  os.chdir('/opt/rust-esp32-std-demo/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-9f3374157bc5d800/out/esp-idf')
  os.chdir('/opt/rust-esp32-std-demo/.embuild/platformio/packages/framework-espidf')
  git apply /opt/rust-esp32-std-demo/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-9f3374157bc5d800/out/esp-idf/patches/missing_riscv_atomics_fix.diff
  os.chdir('/opt/rust-esp32-std-demo/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-9f3374157bc5d800/out/esp-idf')
  os.chdir('/opt/rust-esp32-std-demo/.embuild/platformio/packages/framework-espidf')
  git init
  Initialized empty Git repository in /opt/rust-esp32-std-demo/.embuild/platformio/packages/framework-espidf/.git/
  os.chdir('/opt/rust-esp32-std-demo/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-9f3374157bc5d800/out/esp-idf')
  os.chdir('/opt/rust-esp32-std-demo/.embuild/platformio/packages/framework-espidf')
  git apply /opt/rust-esp32-std-demo/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-9f3374157bc5d800/out/esp-idf/patches/missing_xtensa_atomics_fix.diff
  os.chdir('/opt/rust-esp32-std-demo/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-9f3374157bc5d800/out/esp-idf')
  os.chdir('/opt/rust-esp32-std-demo/.embuild/platformio/packages/framework-espidf')
  git init
  Initialized empty Git repository in /opt/rust-esp32-std-demo/.embuild/platformio/packages/framework-espidf/.git/
  os.chdir('/opt/rust-esp32-std-demo/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-9f3374157bc5d800/out/esp-idf')
  os.chdir('/opt/rust-esp32-std-demo/.embuild/platformio/packages/framework-espidf')
  git apply /opt/rust-esp32-std-demo/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-9f3374157bc5d800/out/esp-idf/patches/pthread_destructor_fix.diff
  os.chdir('/opt/rust-esp32-std-demo/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-9f3374157bc5d800/out/esp-idf')
  os.chdir('/opt/rust-esp32-std-demo/.embuild/platformio/packages/framework-espidf')
  git init
  Initialized empty Git repository in /opt/rust-esp32-std-demo/.embuild/platformio/packages/framework-espidf/.git/
  os.chdir('/opt/rust-esp32-std-demo/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-9f3374157bc5d800/out/esp-idf')
  os.chdir('/opt/rust-esp32-std-demo/.embuild/platformio/packages/framework-espidf')
  git apply /opt/rust-esp32-std-demo/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-9f3374157bc5d800/out/esp-idf/patches/ping_setsockopt_fix.diff
  os.chdir('/opt/rust-esp32-std-demo/target/xtensa-esp32-espidf/debug/build/esp-idf-sys-9f3374157bc5d800/out/esp-idf')


  --- stderr
  Error: Compatible PlatformIO Core not found.
  Reason: PlatformIO executable not found in `/opt/rust-esp32-std-demo/.embuild/platformio/penv/bin`
  error: patch failed: components/lwip/apps/ping/ping_sock.c:274
  error: components/lwip/apps/ping/ping_sock.c: patch does not apply
  *** Error 1
  ========================= [FAILED] Took 165.34 seconds =========================
  Environment    Status    Duration
  -------------  --------  ------------
  debug          FAILED    00:02:45.344
  ==================== 1 failed, 0 succeeded in 00:02:45.344 ====================
  Error: No such file or directory (os error 2)
```
  
</details>

**Comment by ivmarkov** [comment] 2022-01-28 21:20
Duplicate of #56. Once #56 is fixed (soon!) please re-run the whole process.

**Closed by ivmarkov** 2022-01-28 21:20 UTC
